#!/bin/bash
cd "$JAVA_HOME/../"
ls
wget "https://github.com/triplea-game/assets/raw/master/jdk-11.0.5_linux-x64_bin.tar.gz"
tar -xzf jdk-11.0.5_linux-x64_bin.tar.gz
export JAVA_HOME="$(pwd)/jdk-11.0.5"
export PATH=${JAVA_HOME}/bin:$PATH
cd -
java --version

