name: Build and upload Prerelease
on:
  push:
    branches:
      - master
      - release/*
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Create Prerelease
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set tag
        id: setTag
        run: |
          echo "base ref = ${{ github.base.ref }}"
          if [[ "${{ github.base.ref }}" == master ]]; then
              echo "build_number=$(.build/set-build-number ${{ github.run_number }}.pre)" >> $GITHUB_ENV
              echo "build_tag=prerelease" >> $GITHUB_ENV
              echo "is_release=false" >> $GITHUB_ENV
              echo "release_name=Prerelease" >> $GITHUB_ENV
          else
              echo "build_number=$(.build/set-build-number ${{ github.run_number }})" >> $GITHUB_ENV
              echo "build_tag=$build_number" >> $GITHUB_ENV
              echo "is_release=true" >> $GITHUB_ENV
              echo "release_name=Release $build_number" >> $GITHUB_ENV
          fi
      - name: echo version
        run: |
            echo "build_number = ${{ env.build_number }}" 
            echo "build_tag = ${{ env.build_tag }}" 
            echo "is_release = ${{ env.is_release }}" 
            echo "release_name = ${{ env.release_name }}" 
      - name: Build installers
        run: .build/build-installer
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
      - uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true
          # TODO: test behavior if tag DNE
          tag_name: ${{ env.build_tag }}
      - name: Create Github Prerelease
        uses: actions/create-release@v1
        with:        
          tag_name: ${{ env.build_tag }}
          release_name: ${{ env.release_nmae }}
          prerelease: true 
          draft: false
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.build_tag }}
          file: build/artifacts/*
          file_glob: true

